class Color(DefaultColor):
    USERNAME_FG = 15
    USERNAME_BG = 4
    USERNAME_ROOT_BG = 1

    ROOT_INDICATOR_BG = 124
    ROOT_INDICATOR_FG = 226

    HOSTNAME_FG = 254
    HOSTNAME_BG = 166

    HOME_SPECIAL_DISPLAY = True
    PATH_FG = 7
    PATH_BG = 240
    CWD_FG = 15
    SEPARATOR_FG = 249

    READONLY_BG = 1
    READONLY_FG = 7

    REPO_CLEAN_FG = 8
    REPO_CLEAN_BG = 2
    REPO_DIRTY_FG = 8
    REPO_DIRTY_BG = 3

    JOBS_FG = 4
    JOBS_BG = 8

    CMD_PASSED_FG = 15
    CMD_PASSED_BG = 2
    CMD_FAILED_FG = 1
    CMD_FAILED_BG = 8

    SVN_CHANGES_FG = REPO_DIRTY_FG
    SVN_CHANGES_BG = REPO_DIRTY_BG

    VIRTUAL_ENV_BG = 15
    VIRTUAL_ENV_FG = 2
